/** Cloudflare Worker environment bindings (generated by wrangler from wrangler.jsonc). */
interface Env {
  Matchmaker: DurableObjectNamespace;
  Gameroom: DurableObjectNamespace;
  MATCH_TOKEN_SECRET?: string;
  SUPABASE_URL?: string;
  SUPABASE_SERVICE_KEY?: string;
}
